name: Android CI (Debug + Release)

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - name: Install Gradle & wrapper
        working-directory: Lump-v1.0-Pro-Android-Release.zip_unzipped
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install gradle 8.7
          ./gradlew wrapper --gradle-version 8.7
      - name: Build Debug APK
        working-directory: Lump-v1.0-Pro-Android-Release.zip_unzipped
        run: ./gradlew assembleDebug
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Lump-debug-apk
          path: Lump-v1.0-Pro-Android-Release.zip_unzipped/app/build/outputs/apk/debug/*.apk

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3

      - name: Restore keystore from secret
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > Lump-v1.0-Pro-Android-Release.zip_unzipped/app/lump.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Install Gradle & wrapper
        working-directory: Lump-v1.0-Pro-Android-Release.zip_unzipped
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install gradle 8.7
          ./gradlew wrapper --gradle-version 8.7

      - name: Build signed Release
        working-directory: Lump-v1.0-Pro-Android-Release.zip_unzipped
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Lump-release-apk
          path: Lump-v1.0-Pro-Android-Release.zip_unzipped/app/build/outputs/apk/release/*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Lump-v1.0-Pro-Android-Release.zip_unzipped/app/build/outputs/apk/release/*.apk
