name: Android CI (Debug + Release, with Wrapper)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  PROJECT_DIR: 'Lump-v1.0-Pro-Android-Release.zip_unzipped'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Generate Gradle wrapper (8.9)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9
          build-root-directory: ${{ env.PROJECT_DIR }}
          arguments: wrapper --gradle-version 8.9
      - name: Make gradlew executable
        working-directory: ${{ env.PROJECT_DIR }}
        run: chmod +x ./gradlew
      - name: Build Debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: ./gradlew assembleDebug
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Lump-debug-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      - name: Restore keystore from secret
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo "$KEYSTORE_BASE64" | base64 -d > lump.keystore
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Generate Gradle wrapper (8.9)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9
          build-root-directory: ${{ env.PROJECT_DIR }}
          arguments: wrapper --gradle-version 8.9
      - name: Make gradlew executable
        working-directory: ${{ env.PROJECT_DIR }}
        run: chmod +x ./gradlew
      - name: Build signed Release
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: ./gradlew assembleRelease
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Lump-release-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/release/*.apk
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/release/*.apk
